name: Bug Report
description: Create a report to help us improve Serverless Orchestrator
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Serverless Orchestrator are you using?
      placeholder: e.g. 0.1.0 or commit hash
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: e.g. OS, Node version, Go version, Browser
      placeholder: Ubuntu 22.04, Go 1.22, Chrome 114
    validations:
      required: true
