package datadog

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	cftypes "github.com/aws/aws-sdk-go-v2/service/cloudformation/types"
	"github.com/aws/aws-sdk-go-v2/service/sts"

	"github.com/vectorsighttechnologies/serverless-orchestrator/lambda/internal/awsclient"
	"github.com/vectorsighttechnologies/serverless-orchestrator/lambda/internal/config"
	"github.com/vectorsighttechnologies/serverless-orchestrator/lambda/internal/types"
)

const (
	// DatadogStackName is the stack name for Datadog CloudFormation integration role.
	DatadogStackName = "DatadogIntegrationRoleStack"

	// DatadogTemplateBody is a clean, macro-free template that creates the Datadog AWS Integration role directly.
	DatadogTemplateBody = `AWSTemplateFormatVersion: '2010-09-09'
Description: Datadog AWS Integration IAM Role
Parameters:
  ExternalId:
    Type: String
    Description: External ID generated by Datadog
  IAMRoleName:
    Type: String
    Default: DatadogIntegrationRole
    Description: Name of the IAM role to create
Resources:
  DatadogIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::464622532012:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Path: /
      Policies:
        - PolicyName: DatadogAWSIntegrationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - apigateway:GET
                  - autoscaling:Describe*
                  - budgets:ViewBudget
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetTrailStatus
                  - cloudtrail:LookupEvents
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - codedeploy:BatchGet*
                  - codedeploy:List*
                  - directconnect:Describe*
                  - dynamodb:Describe*
                  - dynamodb:List*
                  - ec2:Describe*
                  - ecs:Describe*
                  - ecs:List*
                  - elasticache:Describe*
                  - elasticache:List*
                  - elasticfilesystem:DescribeFileSystems
                  - elasticfilesystem:DescribeTags
                  - elasticloadbalancing:Describe*
                  - elasticmapreduce:Describe*
                  - elasticmapreduce:List*
                  - es:DescribeElasticsearchDomains
                  - es:ListDomainNames
                  - es:ListTags
                  - kinesis:Describe*
                  - kinesis:List*
                  - lambda:List*
                  - logs:Describe*
                  - logs:Get*
                  - logs:FilterLogEvents
                  - logs:TestMetricFilter
                  - organizations:Describe*
                  - organizations:List*
                  - rds:Describe*
                  - rds:List*
                  - route53:List*
                  - s3:GetBucketLocation
                  - s3:GetBucketLogging
                  - s3:GetBucketNotification
                  - s3:GetBucketTagging
                  - s3:ListAllMyBuckets
                  - ses:Get*
                  - ses:List*
                  - sns:GetSubscriptionAttributes
                  - sns:List*
                  - sqs:ListQueues
                  - support:DescribeTrustedAdvisor*
                  - support:RefreshTrustedAdvisorCheck
                  - tag:GetResources
                  - tag:GetTagKeys
                  - tag:GetTagValues
                  - xray:BatchGetTraces
                  - xray:GetTraceSummaries
`
)

// GetIntegrationStatus checks the CloudFormation stack status for the Datadog integration.
func GetIntegrationStatus(
	ctx context.Context,
	clients *awsclient.Factory,
	cfg *config.Config,
) (*types.IntegrationStatusResponse, error) {
	cfClient, err := clients.CloudFormation(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create CloudFormation client: %w", err)
	}

	resp, err := cfClient.DescribeStacks(ctx, &cloudformation.DescribeStacksInput{
		StackName: aws.String(DatadogStackName),
	})
	if err != nil {
		if isStackNotFound(err) {
			return &types.IntegrationStatusResponse{
				Status:      "not_setup",
				LastChecked: time.Now().UTC().Format(time.RFC3339),
			}, nil
		}
		return nil, fmt.Errorf("failed to describe stack %s: %w", DatadogStackName, err)
	}

	if len(resp.Stacks) > 0 {
		stack := resp.Stacks[0]
		status := string(stack.StackStatus)

		result := &types.IntegrationStatusResponse{
			StackName:   DatadogStackName,
			StackStatus: status,
			Method:      "metric_streams",
			LastChecked: time.Now().UTC().Format(time.RFC3339),
		}

		switch {
		case isActiveStatus(stack.StackStatus):
			result.Status = "active"
			roleArn := getRoleArnFromStack(&stack)
			if roleArn != "" {
				// We support dynamic Datadog API registration if an AppKey is supplied
				// We map the App Key dynamically from configuration (falls back to User API key slot)
				appKey := cfg.APIKey
				if appKey != "" {
					err := linkDatadogAccount(ctx, cfg, roleArn, appKey)
					if err != nil {
						result.Status = "error"
						result.Error = "AWS stack deployed, but failed to link with Datadog account: " + err.Error()
					}
				}
			}
		case isInProgressStatus(stack.StackStatus):
			result.Status = "in_progress"
		default:
			result.Status = "error"
			if stack.StackStatusReason != nil && *stack.StackStatusReason != "" {
				result.Error = *stack.StackStatusReason
			} else {
				result.Error = fmt.Sprintf("Stack is in failed state: %s. Please check the AWS CloudFormation Console for details.", status)
			}
		}

		return result, nil
	}

	return &types.IntegrationStatusResponse{
		Status:      "not_setup",
		LastChecked: time.Now().UTC().Format(time.RFC3339),
	}, nil
}

// SetupIntegration deploys Datadog's official main.yaml integration role stack.
func SetupIntegration(
	ctx context.Context,
	clients *awsclient.Factory,
	cfg *config.Config,
	req *types.IntegrationSetupRequest,
) (*types.IntegrationSetupResponse, error) {
	cfClient, err := clients.CloudFormation(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create CloudFormation client: %w", err)
	}

	stsClient, err := clients.STS(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create STS client: %w", err)
	}

	callerIdentity, err := stsClient.GetCallerIdentity(ctx, &sts.GetCallerIdentityInput{})
	if err != nil {
		return nil, fmt.Errorf("failed to get AWS account ID: %w", err)
	}
	awsAccountID := aws.ToString(callerIdentity.Account)

	// Build safe ExternalId seed
	externalID := "datadog-integration-" + awsAccountID

	params := []cftypes.Parameter{
		{ParameterKey: aws.String("ExternalId"), ParameterValue: aws.String(externalID)},
		{ParameterKey: aws.String("IAMRoleName"), ParameterValue: aws.String("DatadogIntegrationRole")},
	}

	// Check if stack already exists
	describeResp, err := cfClient.DescribeStacks(ctx, &cloudformation.DescribeStacksInput{
		StackName: aws.String(DatadogStackName),
	})
	if err == nil && len(describeResp.Stacks) > 0 {
		existingStack := describeResp.Stacks[0]
		status := existingStack.StackStatus

		if isFailedStatus(status) {
			_, err = cfClient.DeleteStack(ctx, &cloudformation.DeleteStackInput{
				StackName: aws.String(DatadogStackName),
			})
			if err != nil {
				return nil, fmt.Errorf("failed to delete failed existing stack %s: %w", DatadogStackName, err)
			}

			deleted := false
			for i := 0; i < 30; i++ {
				time.Sleep(2 * time.Second)
				_, err = cfClient.DescribeStacks(ctx, &cloudformation.DescribeStacksInput{
					StackName: aws.String(DatadogStackName),
				})
				if err != nil && isStackNotFound(err) {
					deleted = true
					break
				}
			}
			if !deleted {
				return nil, fmt.Errorf("timeout waiting for deletion of failed stack %s", DatadogStackName)
			}
		} else if isInProgressStatus(status) {
			return &types.IntegrationSetupResponse{
				Status:  "in_progress",
				StackID: aws.ToString(existingStack.StackId),
			}, nil
		} else if !isFailedStatus(status) && status != cftypes.StackStatusDeleteComplete {
			return &types.IntegrationSetupResponse{
				Status:  "active",
				StackID: aws.ToString(existingStack.StackId),
			}, nil
		}
	}

	createResp, err := cfClient.CreateStack(ctx, &cloudformation.CreateStackInput{
		StackName:    aws.String(DatadogStackName),
		TemplateBody: aws.String(DatadogTemplateBody),
		Parameters:   params,
		Capabilities: []cftypes.Capability{
			cftypes.CapabilityCapabilityIam,
			cftypes.CapabilityCapabilityNamedIam,
			cftypes.CapabilityCapabilityAutoExpand,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create Datadog CF stack: %w", err)
	}

	return &types.IntegrationSetupResponse{
		Status:  "in_progress",
		StackID: aws.ToString(createResp.StackId),
	}, nil
}

// RemoveIntegration deletes the Datadog role stack and unlinks account registration.
func RemoveIntegration(
	ctx context.Context,
	clients *awsclient.Factory,
	cfg *config.Config,
) error {
	cfClient, err := clients.CloudFormation(ctx)
	if err != nil {
		return fmt.Errorf("failed to create CloudFormation client: %w", err)
	}

	stsClient, err := clients.STS(ctx)
	if err != nil {
		return fmt.Errorf("failed to create STS client: %w", err)
	}
	callerIdentity, err := stsClient.GetCallerIdentity(ctx, &sts.GetCallerIdentityInput{})
	if err != nil {
		return fmt.Errorf("failed to get AWS account ID: %w", err)
	}
	awsAccountID := aws.ToString(callerIdentity.Account)

	appKey := cfg.APIKey
	if appKey != "" {
		err := unlinkDatadogAccount(ctx, cfg, awsAccountID, appKey)
		if err != nil {
			fmt.Printf("warning: failed to unlink account from Datadog: %v\n", err)
		}
	}

	_, err = cfClient.DeleteStack(ctx, &cloudformation.DeleteStackInput{
		StackName: aws.String(DatadogStackName),
	})
	if err != nil && !isStackNotFound(err) {
		return fmt.Errorf("failed to delete Datadog stack: %w", err)
	}

	return nil
}

// ─────────────────────────────────────────────────────────────
// Datadog Link Helpers
// ─────────────────────────────────────────────────────────────

func linkDatadogAccount(ctx context.Context, cfg *config.Config, roleArn, appKey string) error {
	parts := strings.Split(roleArn, ":")
	if len(parts) < 5 {
		return fmt.Errorf("invalid Role ARN: %s", roleArn)
	}
	awsAccountID := parts[4]

	endpoint := fmt.Sprintf("https://api.%s/api/v2/integration/aws/accounts", cfg.DDSite)
	if cfg.DDSite == "datadoghq.com" {
		endpoint = "https://api.datadoghq.com/api/v2/integration/aws/accounts"
	}

	payload := map[string]interface{}{
		"data": map[string]interface{}{
			"type": "aws_account",
			"attributes": map[string]interface{}{
				"account_id": awsAccountID,
				"role_name":  "DatadogIntegrationRole",
				"metrics_config": map[string]interface{}{
					"enabled":  true,
					"automute": true,
				},
			},
		},
	}

	bodyBytes, _ := json.Marshal(payload)
	req, err := http.NewRequestWithContext(ctx, "POST", endpoint, bytes.NewBuffer(bodyBytes))
	if err != nil {
		return err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("DD-API-KEY", cfg.DDApiKey)
	req.Header.Set("DD-APPLICATION-KEY", appKey)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		respBytes, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("datadog API returned status %d: %s", resp.StatusCode, string(respBytes))
	}

	return nil
}

func unlinkDatadogAccount(ctx context.Context, cfg *config.Config, awsAccountID, appKey string) error {
	endpoint := fmt.Sprintf("https://api.%s/api/v2/integration/aws/accounts/%s", cfg.DDSite, awsAccountID)
	if cfg.DDSite == "datadoghq.com" {
		endpoint = "https://api.datadoghq.com/api/v2/integration/aws/accounts/" + awsAccountID
	}

	req, err := http.NewRequestWithContext(ctx, "DELETE", endpoint, nil)
	if err != nil {
		return err
	}

	req.Header.Set("DD-API-KEY", cfg.DDApiKey)
	req.Header.Set("DD-APPLICATION-KEY", appKey)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusNoContent {
		respBytes, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("datadog API returned status %d: %s", resp.StatusCode, string(respBytes))
	}

	return nil
}

// ─────────────────────────────────────────────────────────────
// CloudFormation Status Helpers
// ─────────────────────────────────────────────────────────────

func isStackNotFound(err error) bool {
	return strings.Contains(err.Error(), "does not exist") ||
		strings.Contains(err.Error(), "ValidationError")
}

func isActiveStatus(status cftypes.StackStatus) bool {
	return status == cftypes.StackStatusCreateComplete ||
		status == cftypes.StackStatusUpdateComplete
}

func isInProgressStatus(status cftypes.StackStatus) bool {
	return status == cftypes.StackStatusCreateInProgress ||
		status == cftypes.StackStatusUpdateInProgress ||
		status == cftypes.StackStatusDeleteInProgress ||
		status == cftypes.StackStatusUpdateCompleteCleanupInProgress
}

func isFailedStatus(status cftypes.StackStatus) bool {
	return status == cftypes.StackStatusCreateFailed ||
		status == cftypes.StackStatusRollbackFailed ||
		status == cftypes.StackStatusRollbackComplete ||
		status == cftypes.StackStatusDeleteFailed ||
		status == cftypes.StackStatusUpdateRollbackFailed ||
		status == cftypes.StackStatusUpdateRollbackComplete
}

func getRoleArnFromStack(stack *cftypes.Stack) string {
	for _, output := range stack.Outputs {
		val := aws.ToString(output.OutputValue)
		if strings.HasPrefix(val, "arn:aws:iam::") && strings.Contains(val, ":role/") {
			return val
		}
	}
	return ""
}
